# Copyright(c) Microsoft Corporation.
# Licensed under the MIT License.

name: CI/CD Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('**/requirements.txt') }}

    - name: Install dependencies
      run: |
        cat requirements.txt
        cat requirements.txt | grep openai
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        pip list | grep openai

    - name: Check code formatting
      run: |
        ruff format --check src tests

    - name: Run linting
      run: |
        ruff check src tests

    - name: Run type checking
      run: |
        mypy src

    - name: Run tests with coverage
      run: |
        pytest --cov=onemcp --cov-report=xml --cov-report=term-missing

    - name: Upload coverage to Codecov
      if: matrix.python-version == '3.11'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
